### ISSUE TITLE
Unable to Split Chapters 

### ISSUE THREAD

**Issue by lirou4** [openaudible/openaudible#1352]
I am unable to split the chapters for Magic Treehouse Midnight on the Moon audible book. The book has 10 chapters. This is the book: . 
https://www.audible.com/pd/Midnight-on-the-Moon-Audiobook/B073VYFV4P

 This is the error message I get: 

Selected 1 book(s) to split

Skipped Midnight on the Moon 2 or more chapters required

Good:0, Errors:0 Skipped:1
Destination: C:\Users\jlr31\OpenAudible\books

**Comment by openaudible** [comment]
Go to "Get Info" for the book Midnight on the Moon 2 and look at the Chapters tab. If there are no chapters available for the book, we can't split the book by chapters. You could try doing a Controls: Full Resync to get updated chapter data.. and try the "get info" again.

**Comment by openaudible** [comment]
Please try the latest beta. Full resync then check get info for chapters. Then try splitting if you see more than one chapter. If there are no chapters, see if there are chapters on the audible mobile app and let me know.

**Comment by feldegast** [comment]
Full resync is currently broken in beta5 if you have more than one account connected to different servers (what i am currently testing)

**Comment by openaudible** [comment]
Beta 7 should fix it.. Thank you for the reports....

**Comment by lirou4** [comment]
I tried all of the suggestions above. I am still unable to split the book. I did verify that there should be 10 chapters in the book however OpenAudible info on the books says there is only one chapter.  What can I try next?

**Comment by openaudible** [comment]
Select the book. Go to Action Get Info. Go to book report. Copy and paste report to me.      ---- On Thu, 29 Feb 2024 08:29:56 -0800  ***@***.******@***.***> wrote ----  
I tried all of the suggestions above. I am still unable to split the book. I did verify that there should be 10 chapters in the book however OpenAudible info on the books says there is only one chapter.  What can I try next?
