### ISSUE TITLE
Multiple Audible account fails sync

### ISSUE THREAD

**Issue by Snakebiteuk** [openaudible/openaudible#1448]
The following issue exists.

Secondary Audible account connects but fails sync.
Account access successful and verified on audible as working. 

Issue has only happened since update to the latest live release. 

I have tried adding the second account as a new one and this makes no difference.

**Comment by openaudible** [comment]
Check manage accounts under the file menu and make sure they are green. When you do a full resync from the control menu you can check for errors. There shouldn't be any.

**Comment by mshouls** [comment]
I just have one account and I have been getting this error.  under file menu the account is ok and green but there is an error whenever I sync

**Comment by openaudible** [comment]
What is the error message?
Make sure any accounts that are in error are deleted in the File: Manage Accounts

**Comment by mshouls** [comment]
Error message was posted as pic in message.  Error with file sync, you may
need to log in via file controls. There is only one account and it says it
is fine and active.

sent from Moto.

**Comment by openaudible** [comment]
I'm not sure what is going on. Check under File: Manage Accounts. Make sure the account you want is checked and "green". Error accounts need to be deleted and re-connected. 
Send a bug report after any failure and I can look further. (Use About menu: Send Bug Report) and include this issue number.

**Comment by mshouls** [comment]
Sent twice and nothing

**Comment by openaudible** [comment]
We fixed a number of bugs recently. Please make sure any accounts showing an error have been deleted and re-created, under the File: Manage Accounts menu.

**Comment by openaudible** [comment]
Hopefully fixed in latest 4.4.6 or higher.

**Comment by mshouls** [comment]
nope still doesn't work and I have been refunded for it now. I do not know
what "fixes" were done but it would never reconnect to Audible.
