### ISSUE TITLE
Login leads to non-functioning page

### ISSUE THREAD

**Issue by skikibobski** [openaudible/openaudible#1451]
Verified login works, correct region. 
When logged in, it redirects to https://www.amazon.co.uk/ap/ which is a non-functioning page. 
Can redirect to home page but OpenAudible doesn't pick up anything.

**Comment by openaudible** [comment]
Region is set to UK? When I first connect I get a prompt for email or phone.  
You can try again and if it fails, send a bug report from the About menu. Issue 1451.

**Comment by skikibobski** [comment]
Yes, UK. It prompts for an email, then the password, then redirects to the above link.
I'll submit a bug report.

**Comment by openaudible** [comment]
Thank you for the report.
Are you physically located in the UK? Using a VPN?  I haven't gotten any other reports like yours. So not sure what would be different about your situation that would cause that.

**Comment by mad-man111** [comment]
Hello, I'm having the same issue as above. I log in it redirects and asks if i want to go to amazons home page which shows I've logged into the account but doesnt pass this to OA. Attched is an error that appares in the log as I do it
![Open Audible Error](https://github.com/user-attachments/assets/0fa0cddf-8dcf-4fa7-b1e4-db249e07e1c2)

**Comment by openaudible** [comment]
Obscure WebKit bug. What Os are you running?

**Comment by mad-man111** [comment]
Tbf this is running in the OA Docker container. Been working fine for years then tonight brought a licence and updated it and not been happy since.

**Comment by openaudible** [comment]
The error log suggests a WebKit bug. The docker image isn't supported. But might be something that can be fixed with changing a base image or updating a library. 

Are the other people seeing this issue also on docker? Can anyone look to see if the error log looks similar with the WebKit overflow message?

Thanks

**Comment by openaudible** [comment]
@mad-man111 has found an odd bug. I wasn't able to reproduce it. But it shows up in the log as a "RangeError" or Internal browser cookie error. I have a few changes made to the docker file that might help if you build from scratch: https://github.com/openaudible/openaudible_docker

All users with this may need to resort to the File: Manage Accounts, then click the Import Credentials button... and import credentials from another source (run openaudible/libation on another PC/Mac and use those.)

**Comment by longrat11** [comment]
I'm having the same problem as reported above,  just a few days after renewing subscription. 
I don't have access to another PC to import credentials (even if I knew how to)

**Comment by openaudible** [comment]
Hi @longrat11 ,
Looking into this. Did get one bug report but wasn't able to get enough details. Will work on a beta that might help.
Are you in the UK?

**Comment by mad-man111** [comment]
Hello,

I did also try importing the credentials and it failed each time. Unfortunately don't have access to grab the logs at this time.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by openaudible** [comment]
I posted a new beta version 3 that logs additional information if the web login goes to a blank page. 
If it happens, please send a bug report from the About menu.

https://openaudible.org/beta

**Comment by tinyNorman** [comment]
I am in US.  Windows 10. OA version 4.4.6
My US Amazon account was hacked. I changed the password.  Now my US account credentials no longer work. The US account shows status of Error.  So, according the OA Documentation (Managing Accounts) I deleted the account and tried to create it again.  This fails.

OA opens the Amazon login widget, I enter the username/email and password.  I also get redirected to URL https://www.amazon.com/ap/

with error The Web address you entered is not a functioning page on our website.

Console/log 

[CantLogin_log.txt](https://github.com/user-attachments/files/17018114/CantLogin_log.txt)

**Comment by openaudible** [comment]
That looks like the latest version. Looks normal except it doesn't take you to the correct success page. 

Usually there is one or two captcha pages and/or a 2fa page. 

You're able to log into audible.com with your existing email/password? 

You could try another program like libation to see if you're able to log in with their application. You can import credentials from libation and other audible apps into openaudible using the import button on the manage accounts dialog.

**Comment by tinyNorman** [comment]
Yes, I can login to US audible thru Chrome browser using the same credentials.  I will look for Libation and try that.

**Comment by tinyNorman** [comment]
I installed Libation, successfully logged into the account, and LIbation correctly scanned my library.  Under Files -> Manage Accounts -> Import Credentials, OA browses automatically to C:\Users\slb9\Libation and finds the .json files in that folder.  When I click on the AccountsSettings.json that I see there, OA tells me "No new accounts found"

[CantImportLibationCreds.log](https://github.com/user-attachments/files/17019223/CantImportLibationCreds.log)

**Comment by openaudible** [comment]
We fixed the libation import on the latest beta: https://openaudible.org/beta 

Thanks for that report

**Comment by mad-man111** [comment]
Just tried The lastest Docker Build. Still unable to login However I can now import the credentials So all up and running again.

When I try to login it just says: "We're Sorry. The Web address you entered is not a functioning page on our site"

**Comment by openaudible** [comment]
Do you happen to remember if the URL contained the word "maplanding"? That is usually the last page and it does say that -- but the software is supposed to intercept that page/URL and have enough to get your credentials. (Don't paste whole URL.) 
Thanks for the report -- always trying to improve.

**Comment by mad-man111** [comment]
Luckly still had it open. Yes it does contain "manplanding"

**Comment by openaudible** [comment]
If it is still open would you mind sending a bug report from the About Menu Send Bug report? We log a bunch of info and I'm hoping I can get your issue figured out.
