### ISSUE TITLE
It appears that Amazon made some changes on their end which broke the tool

### ISSUE THREAD

**Issue by pogisanpolo** [openaudible/openaudible#301]
![new audible UI](https://user-images.githubusercontent.com/6140959/77848620-9f7fc380-71f8-11ea-8e1a-c82359c858e9.png)

Syncing doesn't seem to work anymore. You can see the discrepancy over here.

**Comment by terrell-r** [comment]
I'm seeing 100 of 654 books. 
![Screenshot_20200329_115308](https://user-images.githubusercontent.com/45837313/77855094-f2835780-71b3-11ea-8aef-d30069c106b1.jpeg)

Full Library scan doesn't appear to complete. Browsing through library is not fetching additional books. 

Mar 29, 2020 11:51:55 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Rescan_Library
Mar 29, 2020 11:54:30 AM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Mar 29, 2020 11:54:36 AM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Mar 29, 2020 11:54:50 AM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Mar 29, 2020 11:55:01 AM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Mar 29, 2020 11:55:10 AM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Mar 29, 2020 11:55:29 AM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Mar 29, 2020 11:55:44 AM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}

**Comment by terrell-r** [comment]
Relaunched with -ae
Mar 29, 2020 12:02:42 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Mar 29, 2020 12:03:10 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Rescan_Library
Mar 29, 2020 12:03:10 PM org.openaudible.desktop.swt.manager.menu.CommandCenter handleMenuAction
SEVERE: ProcessMenu: Rescan_Library
java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$UnmodifiableCollection.addAll(Collections.java:1070)
	at org.openaudible.Audible.findOrphanedFiles(Audible.java:631)
	at org.openaudible.desktop.swt.manager.AudibleGUI.checkOrphansGUI(AudibleGUI.java:273)
	at org.openaudible.desktop.swt.manager.AudibleGUI.refreshLibrary(AudibleGUI.java:344)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:277)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:83)
	at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:358)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:345)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:446)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:72)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:80)
	at org.openaudible.desktop.Application.main(Application.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.org.openaudible.desktop.Application.main(Unknown Source)

**Comment by openaudible** [comment]
That is a known bug in a function called findOrphanedFiles (which can see in other issues.). Need to release a new version. Has to do with finding aax or mp3 files in your library that aren't in the main list of books. I'll try to get a new version out soon.

**Comment by openaudible** [comment]
fixed in 1.6.6 released tonight

**Comment by whit1206** [comment]
@openaudible I just downloaded 1.6.6 from the main website and it is still showing this issue. I connect to my audible library within the window and I can not sync. How do I generate the log window output to share here?
