### ISSUE TITLE
New library view breaks OpenAudible

### ISSUE THREAD

**Issue by openaudible** [openaudible/openaudible#306]
Audible has changed the format of their library view. 
Old view: https://www.audible.com/lib
New view: https://www.audible.com/library/titles
On some accounts and browsers, the old (working) /lib view redirects to /library/titles

This is a new change and is not currently supported.
Edit: I posted a new version 1.6.7 that at least recognizes when you're redirected to the new /library/titles page and gives a warning. Library scans won't work.. unless someone figures out a way to get audible to show the old /lib page. 

You'll have to wait until I can write and test a new library page parser.  Not a quick fix. No ETA at the moment.

**Comment by Drudoo** [comment]
I get the same error. Getting /library/titles in OpenAudible on Windows.

**Comment by pb1051** [comment]
Same. Subscribing.

**Comment by zacpod** [comment]
Same.  New install of OpenAudible.  Library URL shows https://www.audible.com/library/titles and OpenAudible doesn't detect any of the books.

**Comment by Muzzlehatch** [comment]
I just did a fresh install on my new ubuntu machine.  I had it working just fine about January on a different install. 
 It wont catalogue or download any of my books. It will sign onto the library page. 

Here is the Console 
__________________
Apr. 05, 2020 3:57:52 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 1.6.6 for gtk swt 4930 jvm 11.0.6 file charset UTF-8
Apr. 05, 2020 3:57:53 PM org.openaudible.desktop.swt.gui.GUI <init>
SEVERE: Charset not set to utf-8
Apr. 05, 2020 3:57:53 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 1.6.6
Apr. 05, 2020 3:57:53 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1586063084667
Apr. 05, 2020 3:57:53 PM org.openaudible.Audible load
INFO: Loading /home/mark/OpenAudible/books.json
Apr. 05, 2020 3:57:53 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1586063084667
Apr. 05, 2020 3:57:53 PM org.openaudible.Audible checkLibrary
INFO: loaded 0 books.
Apr. 05, 2020 3:57:53 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 169 ms. to complete.
Apr. 05, 2020 3:57:58 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Apr. 05, 2020 3:58:03 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Apr. 05, 2020 3:59:04 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Connect
Apr. 05, 2020 3:59:07 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Apr. 05, 2020 3:59:41 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Apr. 05, 2020 3:59:41 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Apr. 05, 2020 3:59:42 PM org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to AU
________________________

**Comment by Butterfly-Dragon** [comment]
subscribing here, thanks for the update

**Comment by simonexmachina** [comment]
Also seeing this, thanks in advance for a fix :)

**Comment by richardpickett** [comment]
Why would version 1.6.4 work where 1.6.6 and 1.6.5 don't?

**Comment by openaudible** [comment]
@richardpickett I had added a one character bug by mistake when handling a user's click on the download button.. Fixed in 1.6.7.

**Comment by pb1051** [comment]
Because Audible changed the link where you access your library. The
application has not been updated for this change.

**Comment by jbkuma** [comment]
Confirmed fix in 1.6.7

**Comment by Butterfly-Dragon** [comment]
Still have same problem, but at least now i can download the books from the browser.

**Comment by openaudible** [comment]
Fixed in 2.0. 

If you donated to openaudible, be sure to check out https://openaudible.org/donors

**Comment by CrustyApplesniffer** [comment]
Still failed for audible.fr
I've tested the 2.0 version 
Could you re-open the issue ?

**Comment by mcgarrah** [comment]
Still not working for me in 2.0 US EN. Download links fail and no options beyond getting list of books to import which is a step forward from 1.6.6 and 1.6.7.

**Comment by openaudible** [comment]
@CrustyApplesniffer @mcgarrah Lets open a new bug for this for 2.0 if we can't figure this out. 

If you use another web browser and click on a download link, you should get some kind of download for the "Audible helper app". Some books do not have the AAX file format available and may only be listened online or via the audible app. AAXC files are not supported-- so the AAX file is required.  

Can you also send another bug report from 2.0... 
Start with new launch (clears tmp files), connect to audible, do something, and if it fails, send a report with what the expected behavior is. I'm still not totally clear which issues have been fixed and which remain.  Thanks!
