### ISSUE TITLE
Splitting Books Isn't working

### ISSUE THREAD

**Issue by tk2wndy** [openaudible/openaudible#755]
👋 Hi, I’m @tk2wndy I'm new here but hoping to get help.  I have already split a few books into chapters and have not touched the settings but now when I try the little status bar that normally pops up and stays until done just pops up super quick and disappears without doing the split??

Any ideas? I updated the system and restarted the computer but no luck.
Thank you for any help you can give :)

**Comment by openaudible** [comment]
Check the console log window.

**Comment by tk2wndy** [comment]
![image](https://user-images.githubusercontent.com/93408675/139715951-015459ee-417d-416b-b2e9-dfb7c46b6978.png)

**Comment by tk2wndy** [comment]
![image](https://user-images.githubusercontent.com/93408675/139716138-c6c6cd3e-c89c-4e67-9544-e594dbff99b8.png)

**Comment by openaudible** [comment]
Can you paste info from the Console window? That error message you're showing isn't detailed enough. 
If it is a podcast, we don't support podcasts.. The book should be already converted correctly as MP3 or M4B and must include chapter data.. which you can view in the Get Info window.

**Comment by tk2wndy** [comment]
![image](https://user-images.githubusercontent.com/93408675/139721655-f219f2c6-3194-4906-8afe-cbd5c3309a79.png)

**Comment by tk2wndy** [comment]
![image](https://user-images.githubusercontent.com/93408675/139721709-0c5f3c25-6ce9-45da-9b47-c8b31d097a62.png)

**Comment by tk2wndy** [comment]
they are books
5 am club by Robin Sharma is one of them

**Comment by openaudible** [comment]
The console window is different. Under the File menu, it is the first item. I would need the full error message.

**Comment by tk2wndy** [comment]
![image](https://user-images.githubusercontent.com/93408675/139732133-a3d6b45a-4e98-46b7-b2a4-7e793d37f4df.png)

**Comment by tk2wndy** [comment]
Any ideas?

**Comment by openaudible** [comment]
No. The error log is surprisingly empty. 
Can you select the book, do Get Info -CTRL-I, and go to the book report tab.. then select All and copy/paste the info... send it to openaudible at email.tg and we can take a look.  

Alternately, you can go to https://openaudible.org/check.html  and set the AAX file there and we can get the same type of report.

**Comment by tk2wndy** [comment]
Ok, i sent 2 books to the above link but i couldn't tell it they were successfully submitted. Can you check please. The 5am club and Change your brain change your life.
Thank you by the way for all your helpin this
:)

**Comment by tk2wndy** [comment]
Did you see where I sent it? Last time I had this problem my computer worked for splitting chapters no problem but office computer is what I am having this problem with

**Comment by tk2wndy** [comment]
Tried it at home and it worked with no problem. But really need to figure it out here in my office :/  We're you able to see what I sent?

**Comment by tk2wndy** [comment]
Maybe if I uninstall and reinstall???

**Comment by openaudible** [comment]
I didn't see anything in the check aax web page. I think you need to send the aax file. But since it works on a different machine, I imagine it will work on my dev system.

What machine does it fail on and which does it work on (mac, windows, etc) It might be a bug we've seen reported on #765 ... which we have a fix for.. So might have a beta to try tomorrow.

**Comment by openaudible** [comment]
I fixed at least one bug in splitting.. and added additional debug info to the latest beta. Give it a try if you want. Anything from the log window would be helpful... 

https://openaudible.org/beta

**Comment by openaudible** [comment]
new final version posted. THanks for the reports.

**Comment by tk2wndy** [comment]
Still having problems :( I uninstalled and re-downloaded too. Both computers are Window Chrome and i made sure all settings are identical... Any chance we could hop on a zoom?

Wendy Baird

**Comment by openaudible** [comment]
Hi @tk2wndy 

Can you re-create the issue and send a bug report from the About menu with the issue number set to 755 ?

**Comment by openaudible** [comment]
Will keep an eye out for any bug reports. Closing to keep things tidy.
