### ISSUE TITLE
OpenAudible won't open after MacOS update

### ISSUE THREAD

**Issue by kilmerc** [openaudible/openaudible#956]
I updated my laptop recently to MacOS Monterey. Since the update, OpenAudible gets hung up on the initial loading screen and never moves past it. I have uninstalled and reinstalled and it still does it. I am not sure what else to try at this point. I assume others would have been seeing the same issue after the update if it was widespread, but it must just be my own machine. Any possible help or ideas would be appreciated as I cannot use my library anymore at this point.

**Comment by oboe45** [comment]
Have been using Monterey since its release, and have used OpenAudible for many years - works fine for me, my laptop uses the non Mac chip which might be relevant

**Comment by openaudible** [comment]
Definitely make sure you're using the right version -- Intel vs. M1 chip. 
There is a "debug_mac.sh" file inside the application. You can try to run from the Terminal.app if you want.

Open terminal.

```
cd /Applications/OpenAudible.app/Contents/Resources/app
./debug_mac.sh
```
And copy and paste the last few lines of the output.

**Comment by kilmerc** [comment]
<img width="883" alt="image" src="https://user-images.githubusercontent.com/20101738/172296614-42ed2ea4-368d-444e-86ed-e99c32ef12f9.png">

<img width="604" alt="image" src="https://user-images.githubusercontent.com/20101738/172296723-b2d0e3d0-924e-48a4-9b68-12d058f50b37.png">

The screen sits at initializing and the log states the exceptions below:
java.lang.NullPointerException: Cannot read the array length because the return value of "java.io.File.listFiles()" is null
java.lang.NullPointerException: Cannot read the array length because the return value of "java.io.File.listFiles()" is null
Exception in thread "Timer-1" java.lang.NullPointerException: Cannot read the array length because "<local3>" is null

is any of that helpful? Sorry, I am not a programmer so bear with me a little bit. Thanks for your reply!

**Comment by openaudible** [comment]
Hey, that's a great bug report. Very unexpected and the report got it down to the exact line of code. Thank you!

Will post beta 3.5.5.2....

https://openaudible.org/beta

Will make a full minor upgrade as well shortly, as I'm not sure how many people run into this and simply don't report it.

**Comment by openaudible** [comment]
Thank you again. Should be fixed in 3.5.6.

**Comment by kilmerc** [comment]
The beta allowed it to open. I am still having an issue with reading the json file. Nothing has changed about my setup that I am aware of so it is confusing to me what is happening. I have access to the file location still, I have permission to edit the files in that location etc. It may be a long shot, but I will throw the logs in here in to see if you have any clue of what I can do to get my library back. I have a large number of audible and personal files and don't know how to get them back.

Here is the message I get:
![image](https://user-images.githubusercontent.com/20101738/183560389-bc2c0e36-59a4-4620-87b3-313fb82689f6.png)


And here is the full log of the procedure:
Coltons-MacBook-Pro:app colton$ cd /Applications/OpenAudible.app/Contents/Resources/app
Coltons-MacBook-Pro:app colton$ ./debug_mac.sh
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
Aug 08, 2022 9:46:14 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 3.5.8.3 for cocoa swt 4950 jvm 11.0.15
Aug 08, 2022 9:46:14 PM org.openaudible.Directories load
INFO: Directories:{
 "META": "/Users/colton/Library/OpenAudible",
 "APP": "/Applications/OpenAudible.app/Contents/Resources/app",
 "WEB": "/Volumes/Seagate Backup Plus Drive/Transfer to Ethan/Audiobooks",
 "TMP": "/Users/colton/Library/OpenAudible/tmp",
 "BASE": "/Volumes/Seagate Backup Plus Drive/Open Audible"
}
->{
 "META": "/Users/colton/Library/OpenAudible",
 "APP": "/Applications/OpenAudible.app/Contents/Resources/app",
 "MP3": "",
 "ART": "",
 "PDF": "",
 "WEB": "/Volumes/Seagate Backup Plus Drive/Transfer to Ethan/Audiobooks",
 "TMP": "/Users/colton/Library/OpenAudible/tmp",
 "AAX": "",
 "M4B": "",
 "M4A": "",
 "BOOKS": "",
 "BASE": "/Volumes/Seagate Backup Plus Drive/Open Audible"
}
Aug 08, 2022 9:46:14 PM org.openaudible.Directories cleanMetaDir
WARNING: No BASE directory found
Aug 08, 2022 9:46:14 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/colton/Library/OpenAudible/settings.json exists=true size=570
Aug 08, 2022 9:46:14 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1605751527304
Aug 08, 2022 9:46:14 PM org.openaudible.desktop.swt.layout.Theme setTheme
INFO: Setting color theme to dark
Aug 08, 2022 9:46:14 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 3.5.8.3 mac
Aug 08, 2022 9:46:14 PM org.openaudible.desktop.swt.util.shop.PaintShop prefer2x
INFO: useHighDPI=false
Aug 08, 2022 9:46:15 PM org.openaudible.desktop.swt.manager.views.SummaryPanel <init>
SEVERE: Created swt summary panel.
Aug 08, 2022 9:46:15 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/colton/Library/OpenAudible/settings.json exists=true size=570
Aug 08, 2022 9:46:15 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1605751527304
Aug 08, 2022 9:46:15 PM org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to US
Aug 08, 2022 9:46:15 PM org.openaudible.Audible load
INFO: Loading /Volumes/Seagate Backup Plus Drive/Open Audible/books.json
Aug 08, 2022 9:46:15 PM org.openaudible.Audible load
SEVERE: Error loading
java.nio.file.FileSystemException: /Volumes/Seagate Backup Plus Drive/Open Audible/books.json: Operation not permitted
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3206)
	at org.openaudible.util.HTMLUtil.readFile(HTMLUtil.java:27)
	at org.openaudible.books.BookJSON.readBooks(BookJSON.java:134)
	at org.openaudible.Audible.loadBooks(Audible.java:607)
	at org.openaudible.Audible.load(Audible.java:642)
	at org.openaudible.desktop.swt.manager.AudibleGUI.load(AudibleGUI.java:886)
	at org.openaudible.desktop.swt.manager.AudibleGUI$4.run(AudibleGUI.java:962)

Aug 08, 2022 9:46:15 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {Loading} [layout=GridLayout {numColumns=2 marginWidth=12 marginHeight=21 horizontalSpacing=14 verticalSpacing=8}] visible=true input shell:Shell {OpenAudible} [layout=GridLayout {horizontalSpacing=5 verticalSpacing=5}]
Exception in thread "Timer-1" java.lang.NullPointerException
	at org.openaudible.bookfiles.BookFiles.readDirectory(BookFiles.java:214)
	at org.openaudible.bookfiles.BookFiles._updateFileCache(BookFiles.java:149)
	at org.openaudible.bookfiles.BookFiles.updateFileCache(BookFiles.java:130)
	at org.openaudible.bookfiles.BookFiles.checkFileCache(BookFiles.java:260)
	at org.openaudible.bookfiles.BookFiles$1.run(BookFiles.java:77)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Aug 08, 2022 9:46:39 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Error loading books body:Error loading books from file:
/Volumes/Seagate Backup Plus Drive/Open Audible/books.json
File may be damaged, or an application error occurred. 
Error:/Volumes/Seagate Backup Plus Drive/Open Audible/books.json: Operation not permitted
